safe:        false
baseurl:     /
url: http://raphamorim.com/

name: Raphamorim
description: I have a passion for web design and love to create for web and mobile devices. I'm a developer, enthusiast in REST applications and javascript/python evangelist.
url: http://raphamorim.com/
domain: raphamorim.com
commentlinks: true
twitter-username: raphamundi
feedburnerurl: http://feeds.feedburner.com/raphamorim
google-analytics-tracking-id: UA-49746836-1
gems: [jekyll-paginate, jekyll-gist]

source:      .
destination: ./_site
plugins_dir:     ./_plugins
paginate_path: 'blog/page:num'

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   /:title/
paginate: 5

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_codera: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

excerpt_separator: "<!-- more -->"
